# SPDX-FileCopyrightText: 2025 Florian Kauer
# SPDX-License-Identifier: 0BSD

name: Checks
on: [push]
jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1.4.3
        with:
          packages: reuse
      - name: Run reuse
        run: reuse lint
